version: '2'
services:
  seafile:
     image: 10.0.0.96:5000/my_os/centos:seafile_v0.1
     hostname: seafile
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=110
     ports:
       - "38082:8082"
       - "38000:8000"
     volumes:
       - /demo/node/seafile:/data
       - /demo/node/seafile/mysql:/var/lib/mysql
     privileged: true
     command:
       - /usr/sbin/init
     tty: true
  sync-server:
     image: 10.0.0.96:5000/my_os/centos:7.java.sync
     hostname: sync-server
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=110
     ports:
       - "8001:8001"
     volumes:
       - /demo/node/sync-server:/data
     privileged: true
     command:
       - /usr/sbin/init
     tty: true
  material-service:
     image: 10.0.0.96:5000/my_os/centos:7.java.material
     hostname: material-service
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=110
     ports:
       - "9000:9000"
     volumes:
       - /demo/node/material-service:/data
     privileged: true
     command:
       - /usr/sbin/init
     tty: true
  app-server:
     image: 10.0.0.96:5000/my_os/centos:7.java.app
     hostname: app-server
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=110
     ports:
       - "9001:9000"
     volumes:
       - /demo/node/app-server:/data
     privileged: true
     command:
       - /usr/sbin/init
     tty: true
